runtime: nodejs
env: flex
entrypoint: node server.js
automatic_scaling:
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.65
  min_num_instances: 1
  max_num_instances: 10
env_variables:
  NODE_ENV: "production"