name: Build and Deploy to GCP
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci
        working-directory: ./Organization Site

      - name: Build App
        run: npm run build
        working-directory: ./Organization Site

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet
        working-directory: ./Organization Site
