name: Build and deploy Node.js app to Google Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: npm install, build, and test
        run: |
          cd "Organization Site"
          npm install
          npm run build
          dir
      
      - name: Delete old artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: node-app
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./Organization Site/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Google App Engine
        run: |
          cd node-app
          gcloud app deploy app.yaml --quiet --project ${{ secrets.GCLOUD_PROJECT }}
